[pytest]
; DJANGO_SETTINGS_MODULE = config.settings.dev
; DJANGO_SETTINGS_MODULE = config.settings.base because in docer cd cd wont work
python_files = tests.py test_*.py *_tests.py
DJANGO_SETTINGS_MODULE=config.settings.test