name: Django Tests

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres:17

        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest

# Because we moved tests to SQLite and local cache, we don't need PostgreSQL/Redis services in CI initially